plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.148'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

var extractAnalogLib = tasks.register('extractAnalogLib', Sync) {
    from({ zipTree(configurations.analogAudio.singleFile) }) {
        include "META-INF/jarjar/analoglib-neoforge-${analoglib_version}.jar"
        eachFile { path = name }
        includeEmptyDirs = false
    }
    into layout.buildDirectory.dir('analoglib')
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = 'Modrinth'
                url = 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
}

configurations {
    analogAudio {
        canBeConsumed = false
        transitive = false
    }
}

dependencies {
    analogAudio "maven.modrinth:analog-audio:${analog_audio_version}"
    compileOnly files(extractAnalogLib.map { it.destinationDir.toPath().resolve("analoglib-neoforge-${analoglib_version}.jar").toFile() }).builtBy(extractAnalogLib)
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            neo_version      : neo_version,
            mod_id           : mod_id,
            mod_name         : mod_name,
            mod_version      : mod_version,
            mod_authors      : mod_authors,
            mod_description  : mod_description,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
